<thead>
    <tr>
        <th>Name</th>
        <th>Branch</th>
        <th>Contact</th>
        <th>Program</th>
        <th>Benefactor</th>
        <th>University</th>
        <th>Gender</th>
        <th>Birthdate</th>
        <th>Course</th>
        <th>Email</th>
        <th>Remarks</th>
        <th>Action</th>
    </tr>
</thead>